apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctp-server
spec:
  replica: 2
  selector:
   matchLabels:
     app: sctp-server
  template:
    metadata:
      labels:
        app: sctp-server
    spec:
      containers:
      - name: sctp-server
        image: 192.168.49.2:5000/sctp-darn-server:latest
        ports:
        - containerPort: 5000
          protocol: SCTP
