FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    sctp-tools \
    tcpdump \
    gcc \
    make \
    python3 \
    python3-pip \
    && apt-get clean

COPY sctp_darn_server.py /opt/
WORKDIR /opt

CMD ["python3", "sctp_darn_server.py"]
