apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sctp-server
  template:
    metadata:
      labels:
        app: sctp-server
    spec:
      containers:
      - name: sctp-server
        image: $(minikube ip):5000/sctp-darn-server:latest
        ports:
        - containerPort: 5000
          protocol: SCTP
