apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sctp-server
  template:
    metadata:
      labels:
        app: sctp-server
    spec:
      containers:
      - name: sctp-server
        image: debolek/sctp-server:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
