apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sctp-client
  template:
    metadata:
      labels:
        app: sctp-client
    spec:
      containers:
      - name: sctp-client
        image: 192.168.103.2:52307/sctp-client:latest
        command: ["python", "sctp_client.py"]
