apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sctp-server
  template:
    metadata:
      labels:
        app: sctp-server
    spec:
      containers:
      - name: sctp-server
        image: 192.168.103.2:5000/sctp-server:latest
        ports:
        - containerPort: 12345
