kind: Service
apiVersion: v1
metadata:
  name: sctp-server
spec:
  selector:
    app: sctp-server
  ports:
    - protocol: SCTP
      port: 12345
      targetPort: 5000
      nodePort: 31190
  type: NodePort
